/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module get_z_28 (
    input [15:0] s,
    output reg z
  );
  
  
  
  reg z1;
  reg z2;
  reg z3;
  reg z4;
  
  always @* begin
    z1 = !(s[0+0-:1] | s[1+0-:1] | s[2+0-:1] | s[3+0-:1]);
    z2 = !(s[4+0-:1] | s[5+0-:1] | s[6+0-:1] | s[7+0-:1]);
    z3 = !(s[8+0-:1] | s[9+0-:1] | s[10+0-:1] | s[11+0-:1]);
    z4 = !(s[12+0-:1] | s[13+0-:1] | s[14+0-:1] | s[15+0-:1]);
    z = z1 & z2 & z3 & z4;
  end
endmodule
