/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module resetButton_14 (
    output reg [135:0] screen_matrix
  );
  
  
  
  integer i;
  
  always @* begin
    for (i = 1'h0; i < 5'h11; i = i + 1) begin
      screen_matrix[(i)*8+7-:8] = 8'h00;
    end
  end
endmodule
