/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_math_18 (
    input [15:0] x,
    input [15:0] y,
    input [2:0] alufn,
    output reg [15:0] math,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_math_1_add_mul_div;
  wire [1-1:0] M_math_1_z;
  wire [1-1:0] M_math_1_v;
  wire [1-1:0] M_math_1_n;
  reg [2-1:0] M_math_1_alufn;
  reg [16-1:0] M_math_1_x;
  reg [16-1:0] M_math_1_y;
  alu_add_mul_div_23 math_1 (
    .alufn(M_math_1_alufn),
    .x(M_math_1_x),
    .y(M_math_1_y),
    .add_mul_div(M_math_1_add_mul_div),
    .z(M_math_1_z),
    .v(M_math_1_v),
    .n(M_math_1_n)
  );
  
  reg [15:0] math_1_out;
  
  always @* begin
    math = 16'h0000;
    M_math_1_x = x;
    M_math_1_y = y;
    M_math_1_alufn = alufn[0+1-:2];
    math_1_out = M_math_1_add_mul_div;
    z = M_math_1_z;
    v = M_math_1_v;
    n = M_math_1_n;
    
    case (alufn[2+0-:1])
      1'h0: begin
        math = math_1_out;
      end
    endcase
  end
endmodule
