/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_compare_20 (
    input [1:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    
    case (alufn)
      2'h1: begin
        cmp[0+0-:1] = z;
      end
      2'h2: begin
        cmp[0+0-:1] = n ^ v;
      end
      2'h3: begin
        cmp[0+0-:1] = z | (n ^ v);
      end
    endcase
    cmp[1+14-:15] = 15'h0000;
  end
endmodule
