/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_add_mul_div_23 (
    input [1:0] alufn,
    input [15:0] x,
    input [15:0] y,
    output reg [15:0] add_mul_div,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] add;
  
  wire [16-1:0] M_adder_s;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [1-1:0] M_adder_alufn0;
  reg [16-1:0] M_adder_x;
  reg [16-1:0] M_adder_y;
  alu_adder_26 adder (
    .alufn0(M_adder_alufn0),
    .x(M_adder_x),
    .y(M_adder_y),
    .s(M_adder_s),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  
  always @* begin
    add_mul_div = 16'h0000;
    M_adder_alufn0 = alufn[0+0-:1];
    M_adder_x = x;
    M_adder_y = y;
    add = M_adder_s;
    z = M_adder_z;
    v = M_adder_v;
    n = M_adder_n;
    
    case (alufn[1+0-:1])
      1'h0: begin
        add_mul_div = add;
      end
    endcase
  end
endmodule
