/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module endState_13 (
    input endState,
    output reg [143:0] screen_matrix
  );
  
  
  
  integer i;
  
  always @* begin
    screen_matrix = 144'h000000000000000000000000000000000000;
    if (endState == 1'h1) begin
      screen_matrix = 144'hffff0066ffff7e3c18000066ffff7e3c1800;
    end else begin
      if (endState == 1'h0) begin
        screen_matrix = 144'hc0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0ffff;
      end
    end
  end
endmodule
