/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module get_v_29 (
    input s16,
    input x16,
    input y16,
    output reg v
  );
  
  
  
  reg x16_inv;
  reg y16_inv;
  reg s16_inv;
  
  always @* begin
    x16_inv = !x16;
    y16_inv = !y16;
    s16_inv = !s16;
    v = (x16 & y16 & s16_inv) | (x16_inv & y16_inv & s16);
  end
endmodule
