/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module matrixConnect_2 (
    input clk,
    input rst,
    input stop_button,
    input reset_button,
    output reg [143:0] led_matrix,
    output reg [15:0] time_out,
    output reg [15:0] score_out
  );
  
  
  
  reg [143:0] M_matrix_d, M_matrix_q = 144'h000000000000000000000000000000000000;
  wire [4-1:0] M_matrixFSM_level_num_out;
  wire [144-1:0] M_matrixFSM_matrixOut;
  wire [16-1:0] M_matrixFSM_timeout;
  wire [16-1:0] M_matrixFSM_scoreout;
  reg [1-1:0] M_matrixFSM_stop_button;
  reg [1-1:0] M_matrixFSM_reset_button;
  matrixFSM_7 matrixFSM (
    .clk(clk),
    .rst(rst),
    .stop_button(M_matrixFSM_stop_button),
    .reset_button(M_matrixFSM_reset_button),
    .level_num_out(M_matrixFSM_level_num_out),
    .matrixOut(M_matrixFSM_matrixOut),
    .timeout(M_matrixFSM_timeout),
    .scoreout(M_matrixFSM_scoreout)
  );
  
  always @* begin
    M_matrix_d = M_matrix_q;
    
    M_matrixFSM_stop_button = stop_button;
    M_matrixFSM_reset_button = reset_button;
    M_matrix_d = M_matrixFSM_matrixOut;
    time_out = M_matrixFSM_timeout;
    score_out = M_matrixFSM_scoreout;
    led_matrix = M_matrix_q;
  end
  
  always @(posedge clk) begin
    M_matrix_q <= M_matrix_d;
  end
  
endmodule
